services:
  oracle:
    image: 'gvenzl/oracle-free:latest'
    environment:
      - 'ORACLE_PASSWORD=secret'
      - 'APP_USER=DARIOBILL'
      - 'APP_USER_PASSWORD=Rayanparsi1900y'
    ports:
      - '1521'
